<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.dows.framework</groupId>
        <artifactId>rade-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <groupId>org.dows.cloud</groupId>
    <artifactId>dows-router</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <properties>
        <revision>1.0.0-SNAPSHOT</revision>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <mybatis-flex.version>1.7.8</mybatis-flex.version>
        <postgresql.version>42.6.0</postgresql.version>
    </properties>

    <modules>
        <module>router-api</module>
        <module>router-rpc</module>
        <module>router-app</module>
        <module>router-boot</module>
        <module>router-core</module>
        <module>router-rest</module>
        <module>router-biz</module>
        <module>router-handler</module>
        <module>router-dao</module>
        <module>router-email</module>
        <module>router-llm</module>
        <module>router-sms</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>router-rest</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>router-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>router-handler</artifactId>
                <version>${project.version}</version>
            </dependency>


            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>router-dao</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>router-sms</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>router-email</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>router-llm</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>router-biz</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>router-api</artifactId>
                <version>${project.version}</version>
            </dependency>


            <!--          <dependency>
                          <groupId>com.mybatis-flex</groupId>
                          <artifactId>mybatis-flex-spring-boot-starter</artifactId>
                          <version></version>
                      </dependency>-->
            <!--
                        <dependency>
                            <groupId>org.springdoc</groupId>
                            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                        </dependency>
            -->

            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>${postgresql.version}</version>
            </dependency>


        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>