<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dows.router</groupId>
        <artifactId>dows-router</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>router-handler</artifactId>
    <name>router-handler</name>
    <description>处理层</description>

    <dependencies>
        <dependency>
            <groupId>org.dows.router</groupId>
            <artifactId>router-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.dows.router</groupId>
            <artifactId>router-dao</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.checkerframework</groupId>
            <artifactId>checker-qual</artifactId>
            <version>3.42.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>io.debezium</groupId>
            <artifactId>debezium-embedded</artifactId>
            <version>3.2.3.Final</version>
        </dependency>

        <!-- MySQL连接器 -->
        <dependency>
            <groupId>io.debezium</groupId>
            <artifactId>debezium-connector-mysql</artifactId>
            <version>3.2.3.Final</version>
        </dependency>

        <dependency>
            <groupId>io.debezium</groupId>
            <artifactId>debezium-ddl-parser</artifactId>
            <version>3.2.3.Final</version>
        </dependency>

        <!-- 数据库驱动 (MySQL 8.0+) -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>8.2.0</version>
        </dependency>


        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dows.router</groupId>
            <artifactId>router-email</artifactId>
            <version>1.0.0</version>
        </dependency>

    </dependencies>
</project>